### ISSUE TITLE
Improve error mesages for `vidyut.cheda`

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut-py#2]
If the `vidyut_cheda` crate fails, our `vidyut.cheda` wrapper passes through the raw Rust error and doesn't give much insight on how to correct the error.

This is poor UX. In addition to improving the upstream error messages, we should provide informative messages here.

Errors to test:
- sandhi file not found
- sandhi file invalid
- kosha files not found
- kosha files invalid
- model files not found
- model files invalid

**Comment by vipranarayan14** [comment]
Also, it throws the error "index out of bounds: the len is 256 but the index is 2947" when the input text is not in SLP1 (ASCII?). 
The error msg has to be improved. Otherwise, it isn't easy to understand what's going on. I, for instance, thought there was something wrong with the code. And the word "Panic" in the error msg causes real panic 😂!

**Comment by akprasad** [comment]
I'm working on this now along with #3 and #4.

**Comment by akprasad** [comment]
Fixed by adding better pass-through for Rust errors. I also added an error condition for non-ASCII input, for now.
